---
title: "Jesica Formoso's CV"
author: Jesica Formoso
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1gQG_naGWoitYbnINjhXBsMrkWifvXBr_4PfxYvmp4mM/edit?gid=917338460#gid=917338460",  
  pdf_mode = params$pdf_mode
)


```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _jformoso.github.io/cv/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/jformoso/cv/raw/master/formoso_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV |> print_contact_info()
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV |> print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available [on github.com/jformoso/cv](https://github.com/jformoso/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Jesica Formoso {#title}
--------------------------------------------------------------------------------

```{r}
# Note the assignment back to CV. This is so the link stripping works properly in PDF mode
CV <- print_text_block(CV, "intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'education')
```



Selected Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'research_positions')
```




Selected Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------


```{r}
CV <- print_section(CV, 'teaching_positions')
```



Selected Community Developments {data-icon=users}
--------------------------------------------------------------------------------


```{r}
CV <- print_section(CV, 'data_science_writings')
```



Selected Talks and Presentations {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'academic_articles')
```



```{r}
print_links(CV)
```

